name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Set up Go
        uses: actions/setup-go@v5
        id: go
        with:
          go-version: 1.21

      - run: go mod download
      - run: go test ./...
